### ISSUE TITLE
Jeedom v4 compatibility

### ISSUE THREAD

**Issue by Lysandre** [guirem/plugin-marantzdenon#5]
Hello,
Would it be possible to add Jeedom v4 compatibility ?
The plugin worked great before with my Marantz NA8005 and Jeedom v3.
Thank you.

**Comment by solid38** [comment]
I'm interested too ;)

**Comment by solid38** [comment]
Do you have some news about Jeedom 4 compatibility ?
Thanks !

**Comment by Lysandre** [comment]
No. Last time I tried it was still not compatible.

**Comment by solid38** [comment]
Solution :

In this file : 
plugin-marantzdenon/desktop/php/marantzdenon.php

you have to change :
foreach (object::all() as $object) {
to
foreach (jeeObject::all() as $object) {


It works perfectly! :)
